name: Trigger auto deployment for api-chatroom-dev-rs1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/api-chatroom-dev-rs1-AutoDeployTrigger-a57f6b6b-800c-4af7-8ef1-dd004fea62b8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APIMEDHUBPLACEDEVRS1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APIMEDHUBPLACEDEVRS1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APIMEDHUBPLACEDEVRS1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/ChatRoom.Api
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io/esgi
          registryUsername: ${{ secrets.APIMEDHUBPLACEDEVRS1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APIMEDHUBPLACEDEVRS1_REGISTRY_PASSWORD }}
          containerAppName: api-chatroom-dev-rs1
          resourceGroup: chatroom-dev
          imageToBuild: ghcr.io/esgi/api-chatroom-dev-rs1:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


